export const MEN_CLOTHING_LOADING = "MEN_CLOTHING_LOADING";
export const MEN_CLOTHING_FAILURE = "MEN_CLOTHING_FAILURE";
export const MEN_CLOTHING_SUCCESS = "MEN_CLOTHING_SUCCESS";

export const MEN_SHOES_LOADING = "MEN_SHOES_LOADING";
export const MEN_SHOES_FAILURE = "MEN_SHOES_FAILURE";
export const MEN_SHOES_SUCCESS = "MEN_SHOES_SUCCESS";

export const WOMEN_CLOTHING_LOADING = "WOMEN_CLOTHING_LOADING";
export const WOMEN_CLOTHING_FAILURE = "WOMEN_CLOTHING_FAILURE";
export const WOMEN_CLOTHING_SUCCESS = "WOMEN_CLOTHING_SUCCESS";

export const WOMEN_SHOES_LAODING = "WOMEN_SHOES_LOADING";
export const WOMEN_SHOES_FAILURE = "WOMEN_SHOES_FAILURE";
export const WOMEN_SHOES_SUCCESS = "WOMEN_SHOES_SUCCESS";

export const KIDS_SHOES_LOADING = "KIDS_SHOES_LOADING";
export const KIDS_SHOES_FAILURE = "KIDS_SHOES_FAILURE";
export const KIDS_SHOES_SUCCESS = "KIDS_SHEOS_SUCCESS";